export const storeData = [
   { name:"Scott",
    price: 96.46,
    image:"https://m.media-amazon.com/images/I/61L0X1K0TlL._AC_UL320_.jpg",
    amount: 1,
},
 { name:"Olie",
    price: 90.46,
    image:"https://m.media-amazon.com/images/I/51Zu4lrfHFL._AC_UL320_.jpg",
    amount: 3,
},
 { name:"Percy",
    price: 86.46,
    image:"https://m.media-amazon.com/images/I/61KFr3Gz-sL._AC_UL320_.jpg",
    amount: 4,
},
 { name:"Jeremy",
    price: 78.46,
    image:"https://m.media-amazon.com/images/I/51Xmmk-dDuL._AC_UL320_.jpg",
    amount: 2,
}
]